# Generated by Django 3.1.2 on 2020-10-18 12:18

from django.db import migrations, models
import documents.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documentName', models.CharField(max_length=100)),
                ('decumentDesc', models.CharField(blank=True, max_length=200)),
                ('filePath', models.FileField(blank=True, upload_to=documents.models.upload_file)),
                ('version', models.CharField(blank=True, max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['documentName'],
            },
        ),
    ]
