# Generated by Django 3.1.2 on 2020-10-22 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documents',
            old_name='filePath',
            new_name='uploadedFile',
        ),
        migrations.AddField(
            model_name='documents',
            name='uploadedFileName',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
