# Generated by Django 3.1.2 on 2020-10-24 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_auto_20201024_0809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentmeta',
            old_name='metaValue',
            new_name='DocumentMeta',
        ),
        migrations.RemoveField(
            model_name='documentmeta',
            name='documentId',
        ),
        migrations.AddField(
            model_name='documentmeta',
            name='document',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='metavalues', to='documents.documents'),
            preserve_default=False,
        ),
    ]
