# Generated by Django 3.1.2 on 2020-10-31 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_auto_20201031_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentmeta',
            old_name='documentMeta',
            new_name='documentMetaValue',
        ),
    ]
