# Generated by Django 3.1.2 on 2020-11-01 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_auto_20201031_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentmeta',
            name='documentMetaAuto',
            field=models.CharField(blank=True, max_length=1000000),
        ),
        migrations.AlterField(
            model_name='documentmeta',
            name='documentMetaValue',
            field=models.CharField(max_length=1000),
        ),
    ]
